name: Build
on:
  push:
    branches: ["main"]

  pull_request:
    branches: [main]

jobs:
  build-binaries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.8
      - name: Install depencencies
        run: |
          bun install
      - name: Build command
        run: |
          ./build.sh
