name: Create release

# Required secrets:
# - APPLE_CERTIFICATE: Base64-encoded Developer ID certificate (p12 file)
# - APPLE_CERTIFICATE_PASSWORD: Password for the certificate
# - APPLE_ID: Apple ID email
# - APPLE_TEAM_ID: Your Apple Developer Team ID
# - APPLE_APP_SPECIFIC_PASSWORD: App-specific password for Apple ID
# - GITHUB_TOKEN: Automatically provided by GitHub

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.[0-9]*.[0-9]*

jobs:
  build-binaries:
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          npm install

      - name: Build and package
        if: runner.os == 'macOS'
        env:
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
        run: |
          chmod +x ./package-macos.sh
          ./package-macos.sh

      - name: Build Linux binaries
        if: runner.os == 'Linux'
        run: |
          chmod +x ./build.sh
          ./build.sh

      - name: Create release
        if: runner.os == 'Linux'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          repository: ${{ github.repository }}
        run: |
          gh release create "$tag" \
              --repo="$repository" \
              --title="${repository#*/} ${tag#v}" \
              --generate-notes \
              ./releases/*.gz

      - name: Upload macOS Binaries
        if: runner.os == 'macOS'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release upload "$tag" ./releases/tt-dbt-darwin-*.gz
