name: Create release

# Required secrets:
# - APPLE_CERTIFICATE: Base64-encoded Developer ID certificate (p12 file)
# - APPLE_CERTIFICATE_PASSWORD: Password for the certificate
# - APPLE_ID: Apple ID email
# - APPLE_APP_SPECIFIC_PASSWORD: App-specific password for Apple ID
# - GITHUB_TOKEN: Automatically provided by GitHub

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.[0-9]*.[0-9]*

jobs:
  build-binaries:
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          npm install
          npm install -g pkg
          
      - name: Build command
        run: |
          ./build.sh
          
      - name: Import Apple Certificate
        if: runner.os == 'macOS'
        env:
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
        run: |
          echo "$APPLE_CERTIFICATE" | base64 --decode > certificate.p12
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security import certificate.p12 -k build.keychain -P "$APPLE_CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "" build.keychain
          
      - name: Prepare macOS Binaries
        if: runner.os == 'macOS'
        run: |
          # Make binaries executable
          chmod +x ./releases/tt-dbt-darwin-arm64
          chmod +x ./releases/tt-dbt-darwin-x64
          
      - name: Sign macOS Binaries
        if: runner.os == 'macOS'
        run: |
          # Sign both arm64 and x64 binaries
          codesign --force --options runtime,library --timestamp --strict --sign "Developer ID Application" ./releases/tt-dbt-darwin-arm64
          codesign --force --options runtime,library --timestamp --strict --sign "Developer ID Application" ./releases/tt-dbt-darwin-x64
          
      - name: Notarize macOS Binaries
        if: runner.os == 'macOS'
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
        run: |
          # Create a ZIP for notarization
          for arch in arm64 x64; do
            # Create zip
            ditto -c -k --keepParent "./releases/tt-dbt-darwin-$arch" "./releases/tt-dbt-darwin-$arch.zip"
            
            # Submit for notarization
            xcrun altool --notarize-app \
              --primary-bundle-id "com.tokenterminal.tt-dbt.$arch" \
              --username "$APPLE_ID" \
              --password "$APPLE_APP_SPECIFIC_PASSWORD" \
              --file "./releases/tt-dbt-darwin-$arch.zip"
              
            # Wait for notarization to complete and staple
            sleep 60  # Give some time for notarization to process
            xcrun stapler staple "./releases/tt-dbt-darwin-$arch"
            
            # Clean up zip
            rm "./releases/tt-dbt-darwin-$arch.zip"
          done
          
      - name: Compress macOS Binaries
        if: runner.os == 'macOS'
        run: |
          # Compress the signed and notarized binaries
          for arch in arm64 x64; do
            gzip -9 -N -c "./releases/tt-dbt-darwin-$arch" > "./releases/tt-dbt-darwin-$arch.gz"
          done
          
      - name: Create release
        if: runner.os == 'Linux'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          repository: ${{ github.repository }}
        run: |
          gh release create "$tag" \
              --repo="$repository" \
              --title="${repository#*/} ${tag#v}" \
              --generate-notes \
              ./releases/*.gz
              
      - name: Upload macOS Binaries
        if: runner.os == 'macOS'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release upload "$tag" ./releases/tt-dbt-darwin-*.gz
